[tool.black]
line-length = 100
target_version = ['py36']
skip-numeric-underscore-normalization = true
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.mypy_cache
    | \.venv
  )/
)
'''
