# designations are as stated in US Customs and Border Protection Form 1300, under
# Block 5 - VESSEL TYPES
# see https://www.cbp.gov/sites/default/files/assets/documents/2018-Apr/CBP%20Form%201300.pdf
VESSEL_TYPE_CODES = {
    '111': 'Crude Oil Tanker',
    '112': 'Crude/Products Tanker',
    '140': 'Tank Barge',
    '150': 'Other Tanker',
    '210': 'Bulk/Oil Carrier',
    '229': 'Bulk Carrier',
    # '310': 'Container',
    # '325': 'Vehicle Carrier',
    '330': 'General Cargo',
    # '333': 'RO-RO Cargo',
    # '340': 'Dry Cargo Barge',
    # '341': 'Deck Barge',
    # '350': 'Passenger',
    # '410': 'Fish Processing & Catching',
    # '421': 'Drilling Ship',
    # '422': 'Tug/Supply Offshore Support',
    # '431': 'Tug/Tow Boat',
    # '432': 'Pushboat',
    # '492': 'Research/Survey',
    # '493': 'Dredger',
    # '494': 'Yacht',
    # '499': 'Other NEI',
    # '600': 'Lakers Vessels',
}

# ports present in the documents that do not interest us
# because they are not related to any Kpler installations,
# or only do passenger, fish or car ...
BLACKLISTED_PORTS = [
    'ABERDEEN, WA',
    'ALBANY, NY',
    'ASHTABULA/CONNEAUT',
    'ASTORIA, OR',
    'BAR HARBOR, ME',
    'BRUNSWICK, GA',
    'BUFFALO-NIAGARA FALLS',
    'CHARLESTON, SC',
    'CHICAGO, IL',
    'CHRISTIANSTED, VI',
    'CLEVELAND, OH',
    'COOS BAY, OR',
    'CRUZ BAY, VI',
    'DETROIT, MI',
    'DULUTH, MN',
    'ERIE, PA',
    'EUREKA, CA',
    'EVERETT, WA',
    'FAJARDO, PR',
    'FERNANDINA BEACH, FL',
    'FORT PIERCE, FL',
    'FRIDAY HARBOR, WA',
    'GRAND RAPIDS, MI',
    'GREEN BAY, WI',
    'GULFPORT, MS',
    'HILO, HI',
    'KAHULUI, HI',
    'KETCHIKAN, AK',
    'KEY WEST, FL',
    'KONA HI',
    'LONGVIEW, WA',
    'MILWAUKEE, WI',
    'NEW BEDFORD, MA',
    'NEW HAVEN, CT',
    'NEW LONDON, CT',
    'NEWPORT, RI',
    'NORFOLK, VA',
    'OSWEGO, NY',
    'PANAMA CITY, FL',
    'PORT HUENEME, CA',
    'PORT HURON, MI',
    'PORT LAVACA, TX',
    'PORT MANATEE, FL',
    'RICHMOND-PETERSBURG, VA',
    'ROCHESTER, NY',
    'SAGINAW/BAY CITY, MI',
    'SALEM, MA',
    'SAN DIEGO, CA',
    'SAN JUAN, PR',
    'SAULT STE. MARIE, MI',
    'ST AUGUSTINE ARPT UFA',
    'TOLEDO, OH',
    'WEST PALM BEACH, FL',
]
