# Blacklist used to filter relevant cargoes
PRODUCT_BLACKLIST = [
    'accesor',
    'accessor',
    'automobil',
    'calamar',
    'chasis',
    'container',
    'conveyor',
    'equipment',
    'equipo',
    'excavator',
    'fish',
    'generator',
    'package',
    'pallet',
    'parts',
    'pescado',
    'squid',
    'transformer',
    'truck',
    'vehic',
    'vessel',
]
