# FIXME this should be placed in a database
# map Gibson's proprietary country code to ISO 3166-1
# obtained from ISO Online Browsing Platform: https://www.iso.org/obp/ui
FLAG_MAPPING = {
    'ABB': ('AG', 'Antigua and Barbuda'),
    'ABU': ('AE', 'United Arab Emirates'),
    'ADR': ('AD', 'Andorra'),
    'AGL': ('AI', 'Anguilla'),
    'AGO': ('AO', 'Angola'),
    'AJM': ('AE', 'United Arab Emirates'),
    'ALB': ('AL', 'Albania'),
    'ALD': ('AX', 'Åland Islands'),
    'ALG': ('DZ', 'Algeria'),
    'ARG': ('AR', 'Argentina'),
    'ARM': ('AM', 'Armenia'),
    'ARU': ('AW', 'Aruba'),
    'ASM': ('AS', 'American Samoa'),
    'AUS': ('AU', 'Australia'),
    'AUT': ('AT', 'Austria'),
    'AVI': ('VG', 'Virgin Islands (British)'),
    'AZE': ('AZ', 'Azerbaijan'),
    'BAH': ('BS', 'Bahamas'),
    'BBD': ('BB', 'Barbados'),
    'BEL': ('BY', 'Belarus'),
    'BEN': ('BJ', 'Benin'),
    'BER': ('BM', 'Bermuda'),
    'BHU': ('BT', 'Bhutan'),
    'BKF': ('BF', 'Burkina Faso'),
    'BLG': ('BE', 'Belgium'),
    'BNG': ('BD', 'Bangladesh'),
    'BOI': ('BV', 'Bouvet Island'),
    'BOL': ('BO', 'Bolivia'),
    'BOS': ('BA', 'Bosnia and Herzegovina'),
    'BOT': ('BW', 'Botswana'),
    'BRD': ('BI', 'Burundi'),
    'BRI': ('IO', 'British Indian Ocean Territory'),
    'BRN': ('BH', 'Bahrain'),
    'BRU': ('BN', 'Brunei Darussalam'),
    'BRZ': ('BR', 'Brazil'),
    'BUL': ('BG', 'Bulgaria'),
    'BVI': ('VI', 'Virgin Islands (U.S.)'),
    'BZE': ('BZ', 'Belize'),
    'CAN': ('CA', 'Canada'),
    'CAR': ('CF', 'Central African Republic'),
    'CAY': ('KY', 'Cayman Islands'),
    'CHD': ('TD', 'Chad'),
    'CHI': ('GB', 'United Kingdom'),
    'CHL': ('CL', 'Chile'),
    'CHN': ('CN', 'China'),
    'CKI': ('CK', 'Cook Islands'),
    'CMB': ('KH', 'Cambodia'),
    'CMI': ('CX', 'Christmas Island'),
    'CMN': ('CM', 'Cameroon'),
    'CMR': ('KM', 'Comoros'),
    'CNL': ('CA', 'Canada'),
    'COI': ('CC', 'Cocos (Keeling) Islands'),
    'COL': ('CO', 'Colombia'),
    'CON': ('CG', 'Congo'),
    'COS': ('CR', 'Costa Rica'),
    'CRT': ('HR', 'Croatia'),
    'CSR': ('ES', 'Spain'),
    'CUB': ('CU', 'Cuba'),
    'CYP': ('CY', 'Cyprus'),
    'CZR': ('CZ', 'Czechia'),
    'Cur': ('CW', 'Curaçao'),
    'DEN': ('DK', 'Denmark'),
    'DIS': ('DK', 'Denmark'),
    'DJI': ('DJ', 'Djibouti'),
    'DMA': ('DM', 'Dominica'),
    'DOM': ('DO', 'Dominican Republic'),
    'DUB': ('AE', 'United Arab Emirates'),
    'ECU': ('EC', 'Ecuador'),
    'EGY': ('EG', 'Egypt'),
    'ELS': ('SV', 'El Salvador'),
    'EQG': ('GQ', 'Equatorial Guinea'),
    'ERT': ('ER', 'Eritrea'),
    'EST': ('TL', 'Timor-Leste'),
    'ETH': ('ET', 'Ethiopia'),
    'ETN': ('EE', 'Estonia'),
    'FAL': ('FK', 'Falkland Islands (Malvinas)'),
    'FAR': ('FO', 'Faroe Islands'),
    'FAS': ('FO', 'Faroe Islands'),
    'FAT': ('FR', 'France'),
    'FGU': ('GF', 'French Guiana'),
    'FIJ': ('FJ', 'Fiji'),
    'FIN': ('FI', 'Finland'),
    'FPO': ('PF', 'French Polynesia'),
    'FRA': ('FR', 'France'),
    'FUJ': ('AE', 'United Arab Emirates'),
    'GAB': ('GA', 'Gabon'),
    'GAM': ('GM', 'Gambia'),
    'GBI': ('GB', 'United Kingdom'),
    'GDL': ('GP', 'Guadeloupe'),
    'GEO': ('GE', 'Georgia'),
    'GER': ('DE', 'Germany'),
    'GHA': ('GH', 'Ghana'),
    'GIB': ('GI', 'Gibraltar'),
    'GRC': ('GR', 'Greece'),
    'GRE': ('GD', 'Grenada'),
    'GRN': ('GL', 'Greenland'),
    'GUA': ('GT', 'Guatemala'),
    'GUB': ('GW', 'Guinea-Bissau'),
    'GUI': ('GN', 'Guinea'),
    'GUM': ('GU', 'Guam'),
    'GUY': ('GY', 'Guyana'),
    'HAI': ('HT', 'Haiti'),
    'HKG': ('HK', 'Hong Kong'),
    'HMI': ('HM', 'Heard Island and McDonald Islands'),
    'HON': ('HN', 'Honduras'),
    'HUN': ('HU', 'Hungary'),
    'ICL': ('IS', 'Iceland'),
    'IDA': ('ID', 'Indonesia'),
    'IND': ('IN', 'India'),
    'IOM': ('IM', 'Isle of Man'),
    'IRN': ('IR', 'Iran (Islamic Republic of)'),
    'IRP': ('IE', 'Ireland'),
    'IRQ': ('IQ', 'Iraq'),
    'ISR': ('IL', 'Israel'),
    'ITL': ('IT', 'Italy'),
    'IVC': ('CI', 'Côte d\'Ivoire'),
    'JAM': ('JM', 'Jamaica'),
    'JOR': ('JO', 'Jordan'),
    'JPN': ('JP', 'Japan'),
    'KAZ': ('KZ', 'Kazakhstan'),
    'KEN': ('KE', 'Kenya'),
    'KIR': ('KI', 'Kiribati'),
    'KRN': ('KP', 'Korea (Democratic People\'s Republic of)'),
    'KRS': ('KR', 'Korea, Republic of'),
    'KUW': ('KW', 'Kuwait'),
    'KYR': ('KG', 'Kyrgyzstan'),
    'LAO': ('LA', 'Lao People\'s Democratic Republic'),
    'LAV': ('LV', 'Latvia'),
    'LBY': ('LY', 'Libya'),
    'LCN': ('LI', 'Liechtenstein'),
    'LEB': ('LB', 'Lebanon'),
    'LES': ('LS', 'Lesotho'),
    'LIB': ('LR', 'Liberia'),
    'LTH': ('LT', 'Lithuania'),
    'LUX': ('LU', 'Luxembourg'),
    'MAC': ('MO', 'Macao'),
    'MAI': ('MH', 'Marshall Islands'),
    'MAL': ('MY', 'Malaysia'),
    'MAR': ('PT', 'Portugal'),
    'MAU': ('MR', 'Mauritania'),
    'MCD': ('MK', 'North Macedonia'),
    'MDA': ('MD', 'Moldova, Republic of'),
    'MDG': ('MG', 'Madagascar'),
    'MDV': ('MV', 'Maldives'),
    'MEX': ('MX', 'Mexico'),
    'MIC': ('FM', 'Micronesia (Federated States of)'),
    'MLI': ('ML', 'Mali'),
    'MNG': ('MN', 'Mongolia'),
    'MNP': ('MP', 'Northern Mariana Islands'),
    'MNT': ('MS', 'Montserrat'),
    'MOL': ('MD', 'Moldova, Republic of'),
    'MON': ('MC', 'Monaco'),
    'MOR': ('MA', 'Morocco'),
    'MOZ': ('MZ', 'Mozambique'),
    'MTA': ('MT', 'Malta'),
    'MTG': ('ME', 'Montenegro'),
    'MTQ': ('MQ', 'Martinique'),
    'MTS': ('MU', 'Mauritius'),
    'MWI': ('MW', 'Malawi'),
    'MYA': ('MM', 'Malawi'),
    'MYT': ('YT', 'Mayotte'),
    'NBA': ('NA', 'Namibia'),
    'NCL': ('NC', 'New Caledonia'),
    'NEA': ('AN', 'Netherlands Antilles'),
    'NEP': ('NP', 'Nepal'),
    'NGR': ('NE', 'Niger'),
    'NIC': ('NI', 'Nicaragua'),
    'NIG': ('NG', 'Nigeria'),
    'NII': ('NU', 'Niue'),
    'NIS': ('NO', 'Norway'),
    'NOI': ('NF', 'Norfolk Island'),
    'NOR': ('NO', 'Norway'),
    'NTH': ('NL', 'Netherlands'),
    'NUI': ('NR', 'Nauru'),
    'NZL': ('NZ', 'New Zealand'),
    'OMN': ('OM', 'Oman'),
    'PAK': ('PK', 'Pakistan'),
    'PAL': ('PW', 'Palau'),
    'PAN': ('PA', 'Panama'),
    'PAR': ('PY', 'Paraguay'),
    'PER': ('PE', 'Peru'),
    'PHI': ('PH', 'Philippines'),
    'PIT': ('PN', 'Pitcairn'),
    'PNG': ('PG', 'Papua New Guinea'),
    'POL': ('PL', 'Poland'),
    'PRO': ('PR', 'Puerto Rico'),
    'PST': ('ST', 'Sao Tome and Principe'),
    'PTG': ('PT', 'Portugal'),
    'PTO': ('PS', 'Palestine, State of'),
    'QAT': ('QA', 'Qatar'),
    'RAK': ('AE', 'United Arab Emirates'),
    'RCV': ('CV', 'Cabo Verde'),
    'REU': ('RE', 'Réunion'),
    'RIF': ('FR', 'France'),
    'RUM': ('RO', 'Romania'),
    'RUS': ('RU', 'Russian Federation'),
    'RWD': ('RW', 'Rwanda'),
    'SAF': ('ZA', 'South Africa'),
    'SAU': ('SA', 'Saudi Arabia'),
    'SEN': ('SN', 'Senegal'),
    'SEY': ('SC', 'Seychelles'),
    'SHA': ('AE', 'United Arab Emirates'),
    'SHL': ('SH', 'Saint Helena, Ascension and Tristan da Cunha'),
    'SIE': ('SL', 'Sierra Leone'),
    'SKN': ('KN', 'Saint Kitts and Nevis'),
    'SLC': ('LC', 'Saint Lucia'),
    'SLI': ('SB', 'Solomon Islands'),
    'SLO': ('SI', 'Slovenia'),
    'SMO': ('SM', 'San Marino'),
    'SNG': ('SG', 'Singapore'),
    'SNM': ('SR', 'Suriname'),
    'SOM': ('SO', 'Somalia'),
    'SPM': ('PM', 'Saint Pierre and Miquelon'),
    'SPN': ('ES', 'Spain'),
    'SRB': ('RS', 'Serbia'),
    'SRI': ('LK', 'Sri Lanka'),
    'SSI': ('GS', 'South Georgia and the South Sandwich Islands'),
    'SUD': ('SD', 'Sudan'),
    'SVB': ('SJ', 'Svalbard and Jan Mayen'),
    'SVC': ('VC', 'Saint Vincent and the Grenadines'),
    'SVK': ('SK', 'Slovakia'),
    'SWD': ('SE', 'Sweden'),
    'SWZ': ('CH', 'Switzerland'),
    'SYR': ('SY', 'Syrian Arab Republic'),
    'SZL': ('SZ', 'Eswatini'),
    'TAN': ('TZ', 'Tanzania, United Republic of'),
    'TDZ': ('TJ', 'Tajikistan'),
    'THA': ('TH', 'Thailand'),
    'TKC': ('TC', 'Turks and Caicos Islands'),
    'TLU': ('TV', 'Tuvalu'),
    'TOG': ('TG', 'Togo'),
    'TOK': ('TK', 'Tokelau'),
    'TON': ('TO', 'Tonga'),
    'TRI': ('TT', 'Trinidad and Tobago'),
    'TRK': ('TR', 'Turkey'),
    'TUN': ('TN', 'Tunisia'),
    'TUR': ('TM', 'Turkmenistan'),
    'TWN': ('TW', 'Taiwan'),
    'UAE': ('AE', 'United Arab Emirates'),
    'UGA': ('UG', 'Uganda'),
    'UKE': ('UA', 'Ukraine'),
    'UMM': ('AE', 'United Arab Emirates'),
    'UNK': (None, None),  # UNK = unknown
    'URG': ('UY', 'Uruguay'),
    'USA': ('US', 'United States of America'),
    'UZB': ('UZ', 'Uzbekistan'),
    'VAN': ('VU', 'Vanuatu'),
    'VEN': ('VE', 'Venezuela (Bolivarian Republic of)'),
    'VNM': ('VN', 'Viet Nam'),
    'WFU': ('WF', 'Wallis and Futuna'),
    'WSH': ('EH', 'Western Sahara'),
    'WSM': ('WS', 'Samoa'),
    'YEM': ('YE', 'Yemen'),
    'ZAI': ('CD', 'Congo, Democratic Republic of the'),
    'ZBA': ('ZM', 'Zambia'),
    'ZBW': ('ZW', 'Zimbabwe'),
}
