#! /usr/bin/env python
# -*- coding: utf-8 -*-


# make the module available when dynamiquely evaluating confs
from kp_scrapers.cli.commands.doctor import doctor


if __name__ == '__main__':
    doctor()
